[package]
name = "definitions"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
etherparse.workspace = true
serde = { workspace = true , features = ["derive"] }
stypes = { path = "../stypes", features=["rustcore"] }
