export {
    IFilter,
    IFilterFlags,
    IGrabbedContent,
    IGrabbedElement,
    IResultSearchElement,
    ISearchResults,
    ISearchMap,
    TExtractedValuesSrc,
    IExtractedValueSrc,
    TExtractedValues,
    IExtractedMatch,
    IExtractedValue,
    IExtractDTFormatOptions,
    IExtractDTFormatResult,
    IMatchEntity,
    IMapEntity,
    IConcatFile,
    IFileMergeOptions,
} from '../../../../../common/interfaces/interface.rust.api.general';
export { OperationStat } from './debug';
