[package]
name = "extend"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[lints]
workspace = true 

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version="2.0", features=["full","fold"] }
