use super::{frame::Frame, map::Map, nature::Nature};
use std::ops::RangeInclusive;

lazy_static! {
    // If you need to execute some specific test, just define a name
    // of test(s) here.
    static ref RUN_ONLY: Vec<String> = vec![];
    // static ref RUN_ONLY: Vec<String> = vec![String::from("023")];
}

struct MapTest {
    map: Map,
    pub name: String,
    pub actions: Vec<Action>,
}

impl MapTest {
    pub fn create(name: &str, actions: Vec<Action>) -> Self {
        MapTest {
            map: Map::new(),
            name: name.to_string(),
            actions,
        }
    }

    pub fn next(&mut self) -> bool {
        if !RUN_ONLY.is_empty() && !RUN_ONLY.contains(&self.name) {
            println!("[{}]: Skipped", self.name);
            return false;
        }
        if self.actions.is_empty() {
            return false;
        }
        let action = self.actions.remove(0);
        println!("[{}]: Action: {action} ", self.name);
        match action {
            Action::StreamLen(len) => {
                self.map.set_stream_len(len, 4, 2, false).unwrap();
            }
            Action::StreamLenAndUpdate(len) => {
                self.map.set_stream_len(len, 4, 2, true).unwrap();
            }
            Action::CheckLen(len) => {
                if self.map.len() != len {
                    eprintln!(
                        "{}: len of map = {}; expected len = {len}",
                        self.name,
                        self.map.len()
                    );
                }
                assert_eq!(self.map.len(), len);
            }
            Action::BuildBreadcrumbs => {
                self.map.breadcrumbs_build(4, 2).unwrap();
            }
            Action::ExpandBreadcrumbs((sep, offset, above)) => {
                self.map.breadcrumbs_expand(sep, offset, above).unwrap();
            }
            Action::Search(matches) => {
                self.map.insert(&matches, Nature::SEARCH);
            }
            Action::AppendSearch(matches) => {
                self.map
                    .breadcrumbs_insert_and_update(&matches, Nature::SEARCH, 4, 2)
                    .unwrap();
            }
            Action::AddBookmark(position) => {
                self.map
                    .breadcrumbs_insert_and_update(&[position], Nature::BOOKMARK, 4, 2)
                    .unwrap();
            }
            Action::RemoveBookmark(position) => {
                self.map
                    .breadcrumbs_drop_and_update(&[position], Nature::BOOKMARK)
                    .unwrap();
            }
            Action::Insert((pos, nature)) => {
                self.map.insert(&[pos], nature);
            }
            Action::Frame((range, control)) => {
                let mut range = if let Some(range) = range {
                    range
                } else if self.map.is_empty() {
                    RangeInclusive::new(0, 0)
                } else {
                    RangeInclusive::new(0, (self.map.len() - 1) as u64)
                };
                let frame = self.map.frame(&mut range).unwrap();
                if control.len() != frame.indexes.len() {
                    self.print_frame(&frame);
                }
                assert_eq!(control.len(), frame.indexes.len());
                frame.indexes.iter().enumerate().for_each(
                    |(n, (frame_position, frame_natures))| {
                        let (ctrl_position, ctrl_natures) = control.get(n).unwrap();
                        if ctrl_position != frame_position || *frame_natures != *ctrl_natures {
                            self.print_frame(&frame);
                        }
                        assert_eq!(ctrl_position, frame_position);
                        assert_eq!(*frame_natures, *ctrl_natures);
                    },
                );
            }
        }
        !self.actions.is_empty()
    }

    fn print_frame(&self, frame: &Frame) {
        println!("{}", "=".repeat(40));
        println!("Test: {}. Frame", self.name);
        println!("{}", "=".repeat(40));
        frame.indexes.iter().enumerate().for_each(|(n, i)| {
            println!("({n}): {i:?}");
        });
        println!("{}", "=".repeat(40));
    }
}
enum Action {
    // Set len of stream
    StreamLen(u64),
    // Set len of stream and updates breadcrumbs
    StreamLenAndUpdate(u64),
    // Checks a len of map usize - expected len
    CheckLen(usize),
    // Add searches into map
    Search(Vec<u64>),
    // Append searches into map
    AppendSearch(Vec<u64>),
    // Build breadcrumbs
    BuildBreadcrumbs,
    // Extending breadcrumbs
    ExpandBreadcrumbs((u64, u64, bool)),
    // Insert bookmarks into position (used ONLY in breadcrumbs mode)
    AddBookmark(u64),
    // Remove bookmarks from position (used ONLY in breadcrumbs mode)
    RemoveBookmark(u64),
    // Insert nature index into position. For example insert Bookmark in None-Breadcrumbs mode
    Insert((u64, Nature)),
    // Grab Frame (range, expected len, expected content)
    Frame((Option<RangeInclusive<u64>>, Vec<(u64, Nature)>)),
}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Action::StreamLen(len) => format!("StreamLen - {len}"),
                Action::StreamLenAndUpdate(len) => format!("StreamLenAndUpdate - {len}"),
                Action::CheckLen(len) => format!("CheckLen - {len}"),
                Action::Search(matches) => format!("Search - {matches:?}"),
                Action::AppendSearch(matches) => format!("AppendSearch - {matches:?}"),
                Action::BuildBreadcrumbs => "BuildBreadcrumbs".to_string(),
                Action::ExpandBreadcrumbs((sep, offset, above)) =>
                    format!("ExpandBreadcrumbs - sep={sep}; offset={offset}; above={above}"),
                Action::AddBookmark(pos) => format!("AddBookmark - {pos}"),
                Action::RemoveBookmark(pos) => format!("RemoveBookmark - {pos}"),
                Action::Insert((pos, nature)) => format!("Insert - {nature:?} into {pos}"),
                Action::Frame((range, _)) => format!("Frame - {range:?}"),
            }
        )
    }
}

#[test]
fn test() {
    let mut tests: Vec<MapTest> = vec![
        MapTest::create(
            "001",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "002",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::AddBookmark(0),
                Action::AddBookmark(20),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH.union(Nature::BOOKMARK)),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH.union(Nature::BOOKMARK)),
                    ],
                )),
                Action::RemoveBookmark(0),
                Action::RemoveBookmark(20),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "003",
            vec![
                Action::StreamLen(30),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::AddBookmark(23),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BOOKMARK),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (28, Nature::BREADCRUMB),
                        (29, Nature::BREADCRUMB),
                    ],
                )),
                Action::RemoveBookmark(23),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (28, Nature::BREADCRUMB),
                        (29, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "004",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::AddBookmark(19),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BOOKMARK),
                        (20, Nature::SEARCH),
                    ],
                )),
                Action::RemoveBookmark(19),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "005",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::AddBookmark(11),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BOOKMARK),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
                Action::RemoveBookmark(11),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "006",
            vec![
                Action::StreamLen(31),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB_SEPORATOR),
                        (29, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(30),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB_SEPORATOR),
                        (29, Nature::BREADCRUMB),
                        (30, Nature::BOOKMARK),
                    ],
                )),
                Action::RemoveBookmark(30),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB_SEPORATOR),
                        (29, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "007",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "008",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![5, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (3, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB),
                        (5, Nature::SEARCH),
                        (6, Nature::BREADCRUMB),
                        (7, Nature::BREADCRUMB),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "009",
            vec![
                Action::StreamLen(25),
                Action::Search(vec![5, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (3, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB),
                        (5, Nature::SEARCH),
                        (6, Nature::BREADCRUMB),
                        (7, Nature::BREADCRUMB),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "010",
            vec![
                Action::StreamLen(22),
                Action::Search(vec![1, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::SEARCH),
                        (2, Nature::BREADCRUMB),
                        (3, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "011",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![0, 10, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "012",
            vec![
                Action::StreamLen(20),
                Action::Search(vec![10]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "013",
            vec![
                Action::StreamLen(20),
                Action::Search(vec![]),
                Action::CheckLen(0),
                Action::BuildBreadcrumbs,
                Action::CheckLen(0),
            ],
        ),
        MapTest::create(
            "014",
            vec![
                Action::StreamLen(21),
                Action::Search(vec![20]),
                Action::CheckLen(1),
                Action::Insert((10, Nature::BOOKMARK)),
                Action::CheckLen(2),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::BOOKMARK),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "015",
            vec![
                Action::StreamLen(51),
                Action::Search(vec![10, 20, 50]),
                Action::CheckLen(3),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                    ],
                )),
                Action::ExpandBreadcrumbs((35, 10, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (24, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (25, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (26, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (27, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (28, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (29, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (30, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (31, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (32, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (40, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                    ],
                )),
                Action::ExpandBreadcrumbs((40, 10, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (24, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (25, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (26, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (27, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (28, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (29, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (30, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (31, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (32, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (33, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (34, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (35, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (36, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (37, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (38, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (39, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (40, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (41, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (42, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                    ],
                )),
                Action::ExpandBreadcrumbs((45, 15, false)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (23, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (24, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (25, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (26, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (27, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (28, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (29, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (30, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (31, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (32, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (33, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (34, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (35, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (36, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (37, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (38, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (39, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (40, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (41, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (42, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (43, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (44, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (45, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "016",
            vec![
                Action::StreamLen(20),
                Action::Search(vec![10]),
                Action::CheckLen(1),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((4, 2, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((5, 10, false)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (7, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((15, 100, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (7, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::SEARCH),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (13, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (14, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (15, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (16, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (17, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "017",
            vec![
                Action::StreamLen(50),
                Action::Search(vec![0, 20]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (10, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(10),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::BOOKMARK),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AppendSearch(vec![30, 40]),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::SEARCH),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::BOOKMARK),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB_SEPORATOR),
                        (28, Nature::BREADCRUMB),
                        (29, Nature::BREADCRUMB),
                        (30, Nature::SEARCH),
                        (31, Nature::BREADCRUMB),
                        (32, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "018",
            vec![
                Action::StreamLen(50),
                Action::Search(vec![20, 40]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(10),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (4, Nature::BREADCRUMB_SEPORATOR),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::BOOKMARK),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB),
                        (15, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "019",
            vec![
                Action::StreamLen(41),
                Action::Search(vec![20, 40]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                    ],
                )),
                Action::StreamLenAndUpdate(50),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::StreamLenAndUpdate(60),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (50, Nature::BREADCRUMB_SEPORATOR),
                        (58, Nature::BREADCRUMB),
                        (59, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(59),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (50, Nature::BREADCRUMB_SEPORATOR),
                        (58, Nature::BREADCRUMB),
                        (59, Nature::BOOKMARK),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "020",
            vec![
                Action::StreamLen(41),
                Action::Search(vec![20, 40]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                    ],
                )),
                Action::StreamLenAndUpdate(50),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((45, 2, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (43, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (44, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (46, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::StreamLenAndUpdate(60),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (43, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (44, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (51, Nature::BREADCRUMB_SEPORATOR),
                        (58, Nature::BREADCRUMB),
                        (59, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "021",
            vec![
                Action::StreamLen(41),
                Action::Search(vec![20, 40]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                    ],
                )),
                Action::StreamLenAndUpdate(50),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (45, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((45, 2, false)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (44, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::StreamLenAndUpdate(60),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (44, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (52, Nature::BREADCRUMB_SEPORATOR),
                        (58, Nature::BREADCRUMB),
                        (59, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((44, 5, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (43, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (44, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (45, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (52, Nature::BREADCRUMB_SEPORATOR),
                        (58, Nature::BREADCRUMB),
                        (59, Nature::BREADCRUMB),
                    ],
                )),
                Action::StreamLenAndUpdate(100),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::SEARCH),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (38, Nature::BREADCRUMB),
                        (39, Nature::BREADCRUMB),
                        (40, Nature::SEARCH),
                        (41, Nature::BREADCRUMB),
                        (42, Nature::BREADCRUMB),
                        (43, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (44, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (45, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (72, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "022",
            vec![
                Action::StreamLen(100),
                Action::Search(vec![50]),
                Action::BuildBreadcrumbs,
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                        (51, Nature::BREADCRUMB),
                        (52, Nature::BREADCRUMB),
                        (75, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((24, 5, true)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (27, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                        (51, Nature::BREADCRUMB),
                        (52, Nature::BREADCRUMB),
                        (75, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(20),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::BOOKMARK),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                        (51, Nature::BREADCRUMB),
                        (52, Nature::BREADCRUMB),
                        (75, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(1),
                Action::AddBookmark(2),
                Action::AddBookmark(6),
                Action::AddBookmark(99),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BOOKMARK),
                        (2, Nature::BOOKMARK.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BOOKMARK.union(Nature::EXPANDED)),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::BOOKMARK),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                        (51, Nature::BREADCRUMB),
                        (52, Nature::BREADCRUMB),
                        (75, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BOOKMARK),
                    ],
                )),
                Action::StreamLenAndUpdate(200),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BOOKMARK),
                        (2, Nature::BOOKMARK.union(Nature::EXPANDED)),
                        (3, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (4, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (5, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (6, Nature::BOOKMARK.union(Nature::EXPANDED)),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (18, Nature::BREADCRUMB),
                        (19, Nature::BREADCRUMB),
                        (20, Nature::BOOKMARK),
                        (21, Nature::BREADCRUMB),
                        (22, Nature::BREADCRUMB),
                        (35, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                        (50, Nature::SEARCH),
                        (51, Nature::BREADCRUMB),
                        (52, Nature::BREADCRUMB),
                        (75, Nature::BREADCRUMB_SEPORATOR),
                        (98, Nature::BREADCRUMB),
                        (99, Nature::BOOKMARK),
                        (100, Nature::BREADCRUMB),
                        (101, Nature::BREADCRUMB),
                        (149, Nature::BREADCRUMB_SEPORATOR),
                        (198, Nature::BREADCRUMB),
                        (199, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
        MapTest::create(
            "023",
            vec![
                Action::StreamLen(50),
                Action::BuildBreadcrumbs,
                Action::CheckLen(0),
                Action::AddBookmark(25),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BOOKMARK),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (37, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::RemoveBookmark(25),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (37, Nature::BREADCRUMB_SEPORATOR),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::ExpandBreadcrumbs((37, 2, false)),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (36, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(47),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (36, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BOOKMARK.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::RemoveBookmark(47),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (12, Nature::BREADCRUMB_SEPORATOR),
                        (23, Nature::BREADCRUMB),
                        (24, Nature::BREADCRUMB),
                        (25, Nature::BREADCRUMB),
                        (26, Nature::BREADCRUMB),
                        (27, Nature::BREADCRUMB),
                        (36, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(12),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB_SEPORATOR),
                        (10, Nature::BREADCRUMB),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BOOKMARK),
                        (13, Nature::BREADCRUMB),
                        (14, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(3),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (3, Nature::BOOKMARK),
                        (4, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB),
                        (7, Nature::BREADCRUMB_SEPORATOR),
                        (10, Nature::BREADCRUMB),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BOOKMARK),
                        (13, Nature::BREADCRUMB),
                        (14, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
                Action::AddBookmark(6),
                Action::Frame((
                    None,
                    vec![
                        (0, Nature::BREADCRUMB),
                        (1, Nature::BREADCRUMB),
                        (2, Nature::BREADCRUMB),
                        (3, Nature::BOOKMARK),
                        (4, Nature::BREADCRUMB),
                        (5, Nature::BREADCRUMB),
                        (6, Nature::BOOKMARK),
                        (7, Nature::BREADCRUMB),
                        (8, Nature::BREADCRUMB),
                        (9, Nature::BREADCRUMB),
                        (10, Nature::BREADCRUMB),
                        (11, Nature::BREADCRUMB),
                        (12, Nature::BOOKMARK),
                        (13, Nature::BREADCRUMB),
                        (14, Nature::BREADCRUMB),
                        (30, Nature::BREADCRUMB_SEPORATOR),
                        (46, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (47, Nature::BREADCRUMB.union(Nature::EXPANDED)),
                        (48, Nature::BREADCRUMB),
                        (49, Nature::BREADCRUMB),
                    ],
                )),
            ],
        ),
    ];
    tests.iter_mut().for_each(|test| {
        while test.next() {}
        println!("Test \"{}\" OK", test.name);
    });
}
