const path = require('path');
const colors = require('colors/safe');
const fs = require('fs');

const sh = function(task, path, ...commands){
    const jake = require('jake');
    jake.exec(commands.map((command) => {
        return `(cd ${path} && ${command})`;
    }), { printStdout: true, printStderr: true }, () => {
        task.complete();
    });
};

const shNotBreakble = function(task, path, ...commands){
    const jake = require('jake');
    jake.exec(commands.map((command) => {
        return `(cd ${path} && ${command})`;
    }), { printStdout: true, printStderr: true, breakOnError: false }, () => {
        task.complete();
    });
};


class FSController {

    constructor() {
        this._EEntityTypes = {
            file: Symbol(),
            folder: Symbol(),
            all: Symbol()
        };
    }

    getEntities(folder, type) {
        if (!fs.existsSync(folder)) {
            return [];
        }
        const entities = fs.readdirSync(folder);
        if (!(entities instanceof Array)) {
            return [];
        }
        type = typeof type === 'undefined' ? this._EEntityTypes.all : type;
        if (type === this._EEntityTypes.all) {
            return entities;
        }
        const results = [];
        entities.forEach((entity) => {
            const stat = fs.statSync(path.resolve(folder, entity));
            if ((type === this._EEntityTypes.file && !stat.isDirectory()) || (type === this._EEntityTypes.folder && stat.isDirectory())) {
                results.push(entity);
            }
        });
        return results;
    }

    getFiles(folder) {
        return this.getEntities(folder, this._EEntityTypes.file);
    }

    getFolders(folder) {
        return this.getEntities(folder, this._EEntityTypes.folder);
    }

    isFileInFolder(file, folder) {
        return fs.existsSync(path.normalize(path.resolve(folder, file)));
    }
}

const fsController = new FSController();

const ELECTRON_FOLDER = 'electron';
const PLATFORM_FOLDER = 'platform';
const PLATFORM_EXCEPTION_FOLDERS = [
    'platform',
    'node_modules',
    'build',
    'dist'
];
const PROJECTS_EXCEPTION_FOLDERS = [
    'node_modules',
    'build',
    'dist'
];
const LOGO_FILE = 'logo.ascii';

function findAllProjects(target, exceptions, journal = {}) {
    exceptions = exceptions instanceof Array ? exceptions : [];
    const folders = fsController.getFolders(target);
    const projects = [];
    folders.forEach((folder) => {
        if (exceptions.indexOf(folder) !== -1) {
            return;
        }
        const nested = findAllProjects(path.normalize(path.resolve(target, folder)), exceptions, journal);
        projects.push(...nested);
        if (fsController.isFileInFolder(path.normalize(path.resolve(target, folder, 'package.json')))) {
            if (journal[path.basename(folder)] === void 0) {
                projects.push(path.normalize(path.resolve(target, folder)));
                journal[path.basename(folder)] = true;
            }
        }
    });
    return projects;
}

function logo(){
    if (logo.__show !== void 0) { 
        return;
    }
    const file = path.resolve(__dirname, LOGO_FILE);
    if (!fs.existsSync(file)) {
        return;
    }
    const buffer = fs.readFileSync(file);
    logo.__show = true;
    return console.log(colors.yellow(buffer.toString('utf8')));
}
function echo(msg) {
    return `echo "${msg}"`;
}

function echoDec(msg, filler = '*', colorFunc = null) {
    msg = `${filler.repeat(2)} ${msg} ${filler.repeat(2)} `;
    if (colorFunc !== null) {
        return `echo "${colorFunc(`\n${filler.repeat(msg.length - 1)}\n${msg}\n${filler.repeat(msg.length - 1)}\n`)}"` ;
    } else {
        return `echo "\n${filler.repeat(msg.length - 1)}\n${msg}\n${filler.repeat(msg.length - 1)}\n"` ;
    }
}

namespace('solution', function() {

    task('unlink', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PLATFORM_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const target = path.normalize(path.resolve(folder, PLATFORM_FOLDER));
            if (!fs.existsSync(target)) {
                return;
            }
            tasks.push(echo(colors.blue(`unlink: ${target}`)));
            tasks.push(`unlink ${target} & exit 0`);
        });
        if (tasks.length === 0) {
            console.log(`Nothing to unlink. All projects arn't bound`);
            return this.complete();
        }
        console.log(`Found ${tasks.length / 2} bound projects. Projects will be unlinked`);
        sh(this, '.', ...tasks);
    }, {async: true});

    task('link', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PLATFORM_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        const platform = path.normalize(path.resolve(__dirname, PLATFORM_FOLDER));
        projects.forEach((folder) => {
            const target = path.normalize(path.resolve(folder, PLATFORM_FOLDER));
            if (fs.existsSync(target)) {
                console.log(`Project ${folder} is already linked. It will be unlinked before to be linked again.`);
                tasks.push(echo(colors.blue(`unlink: ${target}`)));
                tasks.push(`unlink ${target} & exit 0`);
            }
            tasks.push(echo(colors.blue(`link: ${target}`)));
            tasks.push(`ln -s ${platform} ${target}`);
        });
        sh(this, '.', ...tasks);
    }, {async: true});

    task('clear', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PROJECTS_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const target = path.normalize(path.resolve(folder, 'node_modules'));
            const etc = path.normalize(path.resolve(folder, 'etc'));
            if (fs.existsSync(target)) {
                tasks.push(echo(colors.blue(`clearing: ${target}`)));
                tasks.push(`rm -rf ${target}`);
            }
            fs.existsSync(etc) && tasks.push(`rm -r ${etc}`);
        });
        if (tasks.length === 0) {
            console.log(`No projects to be uninstalled`);
            return this.complete();
        }
        console.log(`Will be uninstalled ${tasks.length} projects.`);
        sh(this, '.', ...tasks);
    }, {async: true});

    task('npm-install', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PROJECTS_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const target = path.normalize(path.resolve(folder, 'node_modules'));
            fs.existsSync(target) && tasks.push(`rm -rf ${target}`);
            tasks.push(echoDec(`Installing NPM in: ${folder}`, '*', colors.green));
            tasks.push(`npm install --prefix ${folder}`);
        });
        if (tasks.length === 0) {
            console.log(`No projects to be installed`);
            return this.complete();
        }
        sh(this, '.', ...tasks);
    }, {async: true});

    task('fix-npm-etc', function() {
        const projects = findAllProjects(path.normalize(__dirname), PROJECTS_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const target = path.normalize(path.resolve(folder, 'etc'));
            fs.existsSync(target) && tasks.push(`rm -rf ${target}`);
        });
        if (tasks.length === 0) {
            console.log(`No projects to be installed`);
            return this.complete();
        }
        sh(this, '.', ...tasks);
    }, {async: true});
    
    task('install', ['solution:npm-install', 'solution:fix-npm-etc']);

    task('upgrade', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PROJECTS_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const packageJson = path.normalize(path.resolve(folder, 'package.json'));
            tasks.push(echoDec(`Checking: ${packageJson}`, '*', colors.green));
            tasks.push(`./node_modules/.bin/npm-check ${folder} -y --no-emoji`);
        });
        if (tasks.length === 0) {
            console.log(`No projects to be upgraded`);
            return this.complete();
        }
        sh(this, '.', ...tasks);
    }, {async: true});

    task('actuality', function() {
        logo();
        const projects = findAllProjects(path.normalize(__dirname), PROJECTS_EXCEPTION_FOLDERS);
        console.log(`Found ${projects.length} projects:\n\t- ${projects.join('\n\t- ')}`);
        const tasks = [];
        projects.forEach((folder) => {
            const packageJson = path.normalize(path.resolve(folder, 'package.json'));
            tasks.push(echoDec(`Checking: ${packageJson}`, '*', colors.green));
            tasks.push(`./node_modules/.bin/npm-check ${folder} --no-emoji`);
        });
        if (tasks.length === 0) {
            console.log(`No projects to be upgraded`);
            return this.complete();
        }
        shNotBreakble(this, '.', ...tasks);
    }, {async: true});

});

namespace('electron', function() {

    namespace('package-file', function() {
        task('create', function() {
            logo();
            const generator = require('./jake.scripts/jake.electron.package');
            const packageJson = JSON.stringify(generator.getPackageJson());
            const packageFilePath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER, 'package.json'));
            if (fs.existsSync(packageFilePath)) {
                console.log(colors.blue(`Remove package.json: ${packageFilePath}`));
                fs.unlinkSync(packageFilePath);
            }
            console.log(colors.blue(`Create new package.json: ${packageFilePath}`));
            fs.writeFileSync(packageFilePath, packageJson);
            this.complete();
        }, {async: true});
        task('remove', function() {
            logo();
            const packageFilePath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER, 'package.json'));
            if (fs.existsSync(packageFilePath)) {
                console.log(colors.blue(`Remove package.json: ${packageFilePath}`));
                fs.unlinkSync(packageFilePath);
            }
            this.complete();
        }, {async: true});
    });

    task('install', function() {
        logo();
        const tasks = [];
        const electronAppPath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER));
        const electronNodeModules = path.normalize(path.resolve(electronAppPath, 'node_modules'));
        if (fs.existsSync(electronNodeModules)) {
            tasks.push(echo(colors.blue(`Remove node_modules files: ${electronNodeModules}`)));
            tasks.push(`rm -rf ${electronNodeModules}`);
        }
        tasks.push(echo(colors.blue(`Installing NPM in: ${electronAppPath}`)));
        tasks.push(`npm install --prefix ${electronAppPath}`);
        sh(this, '.', ...tasks);
    }, {async: true});

    task('compile', function() {
        logo();
        const tasks = [];
        const electronAppPath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER));
        const electronCompiledFolder = path.normalize(path.resolve(electronAppPath, 'compiled'));
        if (fs.existsSync(electronCompiledFolder)) {
            tasks.push(echo(colors.blue(`Remove compiled files: ${electronCompiledFolder}`)));
            tasks.push(`rm -rf ${electronCompiledFolder}`);
        }
        tasks.push(echo(colors.blue(`Installing NPM in: ${electronAppPath}`)));
        tasks.push(`npm run build-ts`);
        sh(this, electronAppPath, ...tasks);
    }, {async: true});

    task('clean', function() {
        logo();
        const tasks = [];
        const electronAppPath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER));
        const electronCompiledFolder = path.normalize(path.resolve(electronAppPath, 'compiled'));
        const electronDistFolder = path.normalize(path.resolve(electronAppPath, 'dist'));
        const electronNodeModules = path.normalize(path.resolve(electronAppPath, 'node_modules'));
        if (fs.existsSync(electronCompiledFolder)) {
            tasks.push(echo(colors.blue(`Remove compiled files: ${electronCompiledFolder}`)));
            tasks.push(`rm -rf ${electronCompiledFolder}`);
        }
        if (fs.existsSync(electronDistFolder)) {
            tasks.push(echo(colors.blue(`Remove compiled files: ${electronDistFolder}`)));
            tasks.push(`rm -rf ${electronDistFolder}`);
        }
        if (fs.existsSync(electronNodeModules)) {
            tasks.push(echo(colors.blue(`Remove compiled files: ${electronNodeModules}`)));
            tasks.push(`rm -rf ${electronNodeModules}`);
        }
        if (tasks.length === 0) {
            return this.complete();
        }
        sh(this, '.', ...tasks);
    }, {async: true});

    task('buildApp', function() {
        logo();
        const tasks = [];
        const electronAppPath = path.normalize(path.resolve(__dirname, ELECTRON_FOLDER));
        const electronDist = path.normalize(path.resolve(electronAppPath, 'dist'));
        if (fs.existsSync(electronDist)) {
            tasks.push(echo(colors.blue(`Remove dist files: ${electronDist}`)));
            tasks.push(`rm -rf ${electronDist}`);
        }
        tasks.push(`npm run build`);
        sh(this, electronAppPath, ...tasks);
    }, {async: true});

    task('build', ['electron:package-file:create', 'electron:install', 'electron:compile' , 'electron:buildApp']);

});
