// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentInfo } from "./attachment";
import type { FilterMatchList } from "./miscellaneous";
import type { NativeError } from "./error";
import type { Progress } from "./progress";
import type { SessionDescriptor } from "./observe";

/**
 * Represents events sent to the client.
 */
export type CallbackEvent = { "StreamUpdated": number } | "FileRead" | { "SearchUpdated": { 
/**
 * The number of logs with matches. Can be `0` if the search is reset on the client side.
 */
found: number, 
/**
 * A map of search conditions and their global match counts within the session.
 * - `String`: The search condition.
 * - `u64`: The count of matches.
 */
stat: Map<string, number>, } } | { "IndexedMapUpdated": { 
/**
 * The number of log entries from search results available for reading.
 */
len: number, } } | { "SearchMapUpdated": FilterMatchList | null } | { "SessionDescriptor": { 
/**
 * Uuid of the observe operation, which adds new `SessionDescriptor`
 */
uuid: string, 
/**
 * Added `SessionDescriptor`
 */
desc: SessionDescriptor, } } | { "SearchValuesUpdated": Map<number, [number, number]> } | { "AttachmentsUpdated": { 
/**
 * The size of the attachment in bytes.
 */
len: number, 
/**
 * The description of the attachment.
 */
attachment: AttachmentInfo, } } | { "Progress": { 
/**
 * The unique identifier of the operation.
 */
uuid: string, 
/**
 * Information about the progress.
 */
progress: Progress, } } | { "SessionError": NativeError } | { "OperationError": { 
/**
 * The unique identifier of the operation that caused the error.
 */
uuid: string, 
/**
 * The error details.
 */
error: NativeError, } } | { "OperationStarted": string } | { "OperationProcessing": string } | { "OperationDone": OperationDone } | "SessionDestroyed";

/**
 * Contains the results of an operation.
 */
export type OperationDone = { 
/**
 * The unique identifier of the operation.
 */
uuid: string, 
/**
 * The results of the operation, if available.
 */
result: Array<number> | null, };
