// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes a match for a search condition.
 */
export type FilterMatch = { 
/**
 * The index (number) of the matching log entry.
 */
index: bigint, 
/**
 * The identifiers of the filters (search conditions) that matched
 * the specified log entry.
 */
filters: Array<number>, };

/**
 * A list of matches for a search condition.
 */
export type FilterMatchList = Array<FilterMatch>;
