// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents events sent to the client.
 */
export type CallbackOptionsEvent = { "LoadingDone": { owner: string, fields: Array<StaticFieldDesc>, } } | { "LoadingErrors": { owner: string, errors: Array<FieldLoadingError>, } } | { "LoadingError": { owner: string, error: string, fields: Array<string>, } } | { "LoadingCancelled": { owner: string, fields: Array<string>, } } | "Destroyed";

export type ComponentOptions = { fields: Array<Field>, uuid: string, };

export type ComponentsOptionsList = { options: Map<string, FieldDesc[]>, };

export type Field = { id: string, value: Value, };

export type FieldDesc = { "Static": StaticFieldDesc } | { "Lazy": LazyFieldDesc };

export type FieldLoadingError = { id: string, err: string, };

export type FieldsValidationErrors = { errors: Map<string, string>, };

export type LazyFieldDesc = { id: string, name: string, desc: string, binding: string | null, };

export type StaticFieldDesc = { id: string, name: string, desc: string, required: boolean, interface: ValueInput, binding: string | null, };

export type Value = { "Boolean": boolean } | { "Number": number } | { "Numbers": Array<number> } | { "String": string } | { "Strings": Array<string> } | { "Directories": Array<string> } | { "Files": Array<string> } | { "File": string } | { "Directory": string } | { "KeyNumber": Map<string, number> } | { "KeyNumbers": Map<string, number[]> } | { "KeyString": Map<string, string> } | { "KeyStrings": Map<string, string[]> };

export type ValueInput = { "Checkbox": boolean } | { "Number": number } | { "String": string } | { "Numbers": [Array<number>, number] } | { "Strings": [Array<string>, string] } | { "NamedBools": Array<[string, boolean]> } | { "NamedNumbers": Array<[string, number]> } | { "NamedStrings": Array<[string, string]> } | { "KeyNumber": Map<string, number> } | { "KeyNumbers": Map<string, number[]> } | { "KeyString": Map<string, string> } | { "KeyStrings": Map<string, string[]> } | { "NestedNumbersMap": Map<string, Map<string, Map<string, number>>> } | { "NestedStringsMap": Map<string, Map<string, Map<string, string>>> } | "Directories" | { "Files": Array<string> } | { "File": Array<string> } | "Directory" | { "Bound": { output: ValueInput, inputs: Array<ValueInput>, } };
