"use strict";
var VIEW_BAR_ADD_FAVORITE_RESPONSE = (function () {
    function VIEW_BAR_ADD_FAVORITE_RESPONSE() {
    }
    return VIEW_BAR_ADD_FAVORITE_RESPONSE;
}());
exports.EVENT_VIEW_BAR_ADD_FAVORITE_RESPONSE = VIEW_BAR_ADD_FAVORITE_RESPONSE;
//# sourceMappingURL=VIEW_BAR_ADD_FAVORITE_RESPONSE.js.map