site_name: Chipmunk Log Analyzer & Viewer
site_url: https://esrlabs.github.io/chipmunk/
docs_dir: docs
theme:
  name: material
nav:
  - Overview: index.md
  - Installation: installation.md
  - Search: search.md
  - Charts: charts.md
  - Navigation: navigation.md
  - Teamwork: teamwork.md
  - Chipmunk CLI Tool: cli.md
  - Plugins:
    - Development Guide: plugins/development-guide.md
    - Integration in Chipmunk UI: plugins/integration-ui.md
    - Plugins API Crate: plugins/plugins-api.md
    - C/C++: plugins/cpp.md
  - Development: 
    - Chipmunk Core:
      - Overview: development/core/core.md
      - Producer: development/core/producer.md
      - Plugins: development/core/plugins.md
  - Contributing: 
    - Welcome: contributing/welcome.md
    - Getting Started: contributing/getting-started.md
    - Development Guide: contributing/development-guide.md
    - Debugging: contributing/debugging.md
    - Developer CLI Tool: contributing/dev-cli.md

