[package]
name = "bufread"
version = "0.1.1"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rand.workspace = true

[[bench]]
name = "buffer_benches"
harness = false

[[bench]]
name = "reader_benches"
harness = false
