require './scripts/elements/platform'
require './scripts/elements/bindings'
require './scripts/elements/client'
require './scripts/elements/holder'
require './scripts/elements/matcher'
require './scripts/elements/launcher'
require './scripts/elements/release'
