[package]
name = "example"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "example"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.5.1"

[dependencies]
crossbeam-channel = "0.5.0"
dlt = { path = "../../indexer/dlt" }
indexer_base = { path = "../../indexer/indexer_base" }
log = "0.4"
merging = { path = "../../indexer/merging" }
neon = { version = "0.5", features = ["event-handler-api"] }
processor = { path = "../../indexer/processor" }