mod err;
mod gen;

pub(crate) use err::*;
pub(crate) use serde::Serialize;
pub(crate) use serde_wasm_bindgen::{from_value, Serializer};
pub(crate) use stypes::*;
pub(crate) use wasm_bindgen::prelude::*;

gen_encode_decode_fns!(ObserveOptions);
gen_encode_decode_fns!(MulticastInfo);
gen_encode_decode_fns!(UdpConnectionInfo);
gen_encode_decode_fns!(ParserType);
gen_encode_decode_fns!(DltParserSettings);
gen_encode_decode_fns!(SomeIpParserSettings);
gen_encode_decode_fns!(Transport);
gen_encode_decode_fns!(ProcessTransportConfig);
gen_encode_decode_fns!(SerialTransportConfig);
gen_encode_decode_fns!(TCPTransportConfig);
gen_encode_decode_fns!(UDPTransportConfig);
gen_encode_decode_fns!(FileFormat);
gen_encode_decode_fns!(ObserveOrigin);
gen_encode_decode_fns!(FoldersScanningResult);
gen_encode_decode_fns!(CommandOutcome<FoldersScanningResult>);
gen_encode_decode_fns!(CommandOutcome<SerialPortsList>);
gen_encode_decode_fns!(CommandOutcome<()>);
gen_encode_decode_fns!(CommandOutcome<i64>);
gen_encode_decode_fns!(CommandOutcome<Option<String>>);
gen_encode_decode_fns!(CommandOutcome<String>);
gen_encode_decode_fns!(CommandOutcome<bool>);
gen_encode_decode_fns!(CallbackEvent);
gen_encode_decode_fns!(NativeError);
gen_encode_decode_fns!(NativeErrorKind);
gen_encode_decode_fns!(Severity);
gen_encode_decode_fns!(OperationDone);
gen_encode_decode_fns!(LifecycleTransition);
gen_encode_decode_fns!(AttachmentInfo);
gen_encode_decode_fns!(AttachmentList);
gen_encode_decode_fns!(Notification);
gen_encode_decode_fns!(Progress);
gen_encode_decode_fns!(Ticks);
gen_encode_decode_fns!(Ranges);
gen_encode_decode_fns!(SourceDefinition);
gen_encode_decode_fns!(Sources);
gen_encode_decode_fns!(SdeRequest);
gen_encode_decode_fns!(SdeResponse);
gen_encode_decode_fns!(GrabbedElement);
gen_encode_decode_fns!(GrabbedElementList);
gen_encode_decode_fns!(AroundIndexes);
gen_encode_decode_fns!(FilterMatch);
gen_encode_decode_fns!(FilterMatchList);
