//! Function to cleanup temp files and directories created by Chipmunk and haven't
//! gotten cleaned up properly.

use std::{
    fs, io,
    path::{Path, PathBuf},
    time::{Duration, SystemTime},
};

use crate::paths::{get_chipmunk_downloads_dir, get_streams_dir};

/// Cleanup temporary files that is generated by Chipmunk on previous sessions.
///
/// If provided, `download_prefix` removes matching direct child directories in
/// the downloads directory in the same scan as age-based cleanup.
pub fn cleanup_temp_files(download_prefix: Option<&str>) -> Result<(), Vec<stypes::NativeError>> {
    let res_tmp = cleanup_temp_dir();
    let res_download = cleanup_download_dir(download_prefix);

    let errs: Vec<_> = [res_tmp, res_download]
        .into_iter()
        .filter_map(|res| res.err())
        .collect();

    if errs.is_empty() { Ok(()) } else { Err(errs) }
}

/// Iterates through chipmunk temporary directory and remove the entries older
/// than one months.
fn cleanup_temp_dir() -> Result<(), stypes::NativeError> {
    let tmp_dir = get_streams_dir()?;

    const ONE_MONTHS_SECONDS: u64 = 30 * 60 * 24 * 60;
    let modified_limit = SystemTime::now()
        .checked_sub(Duration::from_secs(ONE_MONTHS_SECONDS))
        .ok_or_else(|| stypes::NativeError {
            severity: stypes::Severity::ERROR,
            kind: stypes::NativeErrorKind::Io,
            message: Some(String::from(
                "Error while calculating modification time limit",
            )),
        })?;

    cleanup_dir(&tmp_dir, modified_limit)?;

    Ok(())
}

/// Iterates through chipmunk downloads directory and remove stale entries or
/// fresh matching download directories.
fn cleanup_download_dir(prefix: Option<&str>) -> Result<(), stypes::NativeError> {
    let download_dir = get_chipmunk_downloads_dir()?;
    if !download_dir.exists() {
        return Ok(());
    }

    const ONE_WEEK_SECONDS: u64 = 7 * 60 * 24 * 60;
    let modified_limit = SystemTime::now()
        .checked_sub(Duration::from_secs(ONE_WEEK_SECONDS))
        .ok_or_else(|| stypes::NativeError {
            severity: stypes::Severity::ERROR,
            kind: stypes::NativeErrorKind::Io,
            message: Some(String::from(
                "Error while calculating modification time limit",
            )),
        })?;

    cleanup_download_entries(&download_dir, modified_limit, prefix)?;

    Ok(())
}

// Clean files and directory within the given path that have a modified time older than
// the given modified date limit
fn cleanup_dir(path: &Path, modified_date_limit: SystemTime) -> io::Result<()> {
    if !path.exists() {
        return Ok(());
    }

    fs::read_dir(path)?
        .flat_map(Result::ok)
        .filter(|p| is_stale_entry(p, modified_date_limit))
        .map(|entry| entry.path())
        .try_for_each(remove_entry)
}

fn cleanup_download_entries(
    path: &Path,
    modified_date_limit: SystemTime,
    prefix: Option<&str>,
) -> io::Result<()> {
    if !path.exists() {
        return Ok(());
    }

    fs::read_dir(path)?
        .flat_map(Result::ok)
        .filter(|entry| {
            is_stale_entry(entry, modified_date_limit) || is_prefixed_dir(entry, prefix)
        })
        .map(|entry| entry.path())
        .try_for_each(remove_entry)
}

fn is_stale_entry(entry: &fs::DirEntry, modified_date_limit: SystemTime) -> bool {
    entry
        .metadata()
        .is_ok_and(|meta| meta.modified().is_ok_and(|date| date < modified_date_limit))
}

fn is_prefixed_dir(entry: &fs::DirEntry, prefix: Option<&str>) -> bool {
    let Some(prefix) = prefix.filter(|prefix| !prefix.is_empty()) else {
        return false;
    };

    entry.file_type().is_ok_and(|file_type| file_type.is_dir())
        && entry
            .file_name()
            .to_str()
            .is_some_and(|name| name.starts_with(prefix))
}

fn remove_entry(path: PathBuf) -> io::Result<()> {
    if path.is_dir() {
        fs::remove_dir_all(path)
    } else if path.is_file() {
        fs::remove_file(path)
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::{
        fs::{self, File},
        thread,
        time::{Duration, SystemTime},
    };

    use super::{cleanup_dir, cleanup_download_entries};

    #[test]
    fn cleanup_download_entries_removes_matching_prefix_dirs() {
        let tempdir = tempfile::tempdir().unwrap();
        let temp_path = tempdir.path();

        let current_update = temp_path.join("update_4.0.1_123");
        fs::create_dir_all(current_update.join("artifact/archive-stage-123")).unwrap();
        File::create(current_update.join("artifact/archive-stage-123/chipmunk-update.ps1"))
            .unwrap();

        let other_update = temp_path.join("update_4.0.2_123");
        fs::create_dir(&other_update).unwrap();

        let matching_file = temp_path.join("update_4.0.1_file");
        File::create(&matching_file).unwrap();

        let old_limit = SystemTime::now()
            .checked_sub(Duration::from_secs(3600))
            .unwrap();
        cleanup_download_entries(temp_path, old_limit, Some("update_4.0.1_")).unwrap();

        assert!(!current_update.exists());
        assert!(other_update.exists());
        assert!(matching_file.exists());
    }

    #[test]
    fn cleanup_download_entries_ignores_empty_prefix() {
        let tempdir = tempfile::tempdir().unwrap();
        let temp_path = tempdir.path();

        let update_dir = temp_path.join("update_4.0.1_123");
        fs::create_dir(&update_dir).unwrap();

        let old_limit = SystemTime::now()
            .checked_sub(Duration::from_secs(3600))
            .unwrap();
        cleanup_download_entries(temp_path, old_limit, Some("")).unwrap();

        assert!(update_dir.exists());
    }

    #[test]
    fn test_cleanup_dir() {
        // Create temporary directory with some entries
        let tempdir = tempfile::tempdir().unwrap();
        let temp_path = tempdir.path();

        let dir = temp_path.join("dir");
        fs::create_dir(&dir).unwrap();
        let sub_file = dir.join("sub_file");
        _ = File::create(&sub_file).unwrap();
        let file = temp_path.join("file");
        _ = File::create(&file).unwrap();

        let entries = [dir, sub_file, file];

        // Make sure there differences in modification time and current time.
        thread::sleep(Duration::from_millis(50));

        // Cleaning up with time stamp one day ago must not remove anything.
        let past = SystemTime::now()
            .checked_sub(Duration::from_secs(3600))
            .unwrap();
        cleanup_dir(temp_path, past).unwrap();
        for entry in &entries {
            assert!(entry.exists());
        }

        // Cleaning up with now must remove all files and directories.
        cleanup_dir(temp_path, SystemTime::now()).unwrap();

        // Temp directory itself shouldn't be removed.
        assert!(temp_path.exists());

        for entry in entries {
            assert!(!entry.exists());
        }
    }
}
