/// Ephemeral signals generated by UI components during a render frame.
///
/// These signals are collected in `SessionShared` and processed by the
/// `SessionUI` controller at the end of the frame to handle state changes
/// that require mutable access to the parent.#[derive(Debug, Clone)]
#[derive(Debug, Clone)]
pub enum SessionSignal {
    /// Indicates that search has been dropped in last frame.
    SearchDropped,
}
