[package]
name = "wasm-bindings"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ansi-to-html = { version = "0.1.2", features = ["lazy-init"] }
fuzzy-matcher = "0.3"
regex = "1"
serde_json = "1.0"
strip-ansi-escapes = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
