[package]
name = "launcher"
version = "0.1.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>", "oliver.mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
flate2 = "1.0"
dirs = "2.0"
log = "0.4.8"
log4rs = "0.8.3"
regex = "1"
