[package]
name = "launcher"
version = "0.1.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
flate2 = "1.0.11"
dirs = "2.0.2"
