use crate::*;

try_into_js!(PluginParserSettings);
try_into_js!(PluginParserGeneralSettings);
try_into_js!(PluginByteSourceSettings);
try_into_js!(PluginByteSourceGeneralSettings);
try_into_js!(PluginConfigItem);
try_into_js!(PluginConfigValue);
try_into_js!(PluginConfigSchemaType);
try_into_js!(PluginConfigSchemaItem);
try_into_js!(PluginEntity);
try_into_js!(PluginMetadata);
try_into_js!(PluginType);
try_into_js!(PluginInfo);
try_into_js!(InvalidPluginEntity);
try_into_js!(SemanticVersion);
try_into_js!(RenderOptions);
try_into_js!(ParserRenderOptions);
try_into_js!(PluginsList);
try_into_js!(InvalidPluginsList);
try_into_js!(PluginsPathsList);
