[package]
name = "updater"
version = "0.2.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>", "oliver.mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
dirs = "3.0.1"
log = "0.4.8"
log4rs = "0.13.0"
anyhow = "1.0"
base = { path = "../base" }
