// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentInfo = { uuid: string, filepath: string, name: string, ext: string, size: bigint, mime: string, messages: Array<bigint>, };
