// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentInfo } from "./AttachmentInfo";

export type AttachmentInfoList = { elements: Array<AttachmentInfo>, };
