// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationPath } from './DestinationPath';
import type { SessionCreatingFail } from './SessionCreatingFail';
import type { Communication } from './Communication';
import type { OperationNotSupported } from './OperationNotSupported';
import type { IoOperation } from './IoOperation';
import type { InvalidData } from './InvalidData';
import type { InvalidArgs } from './InvalidArgs';
import type { Process } from './Process';
import type { Protocol } from './Protocol';
import type { SearchError } from './SearchError';
import type { MultipleInitCall } from './MultipleInitCall';
import type { SessionUnavailable } from './SessionUnavailable';
import type { NativeError } from './NativeError';
import type { Grabbing } from './Grabbing';
import type { Sde } from './Sde';

export type Error =
    | { DestinationPath: DestinationPath }
    | { SessionCreatingFail: SessionCreatingFail }
    | { Communication: Communication }
    | { OperationNotSupported: OperationNotSupported }
    | { InvalidData: InvalidData }
    | { IoOperation: IoOperation }
    | { InvalidArgs: InvalidArgs }
    | { Process: Process }
    | { Protocol: Protocol }
    | { SearchError: SearchError }
    | { MultipleInitCall: MultipleInitCall }
    | { SessionUnavailable: SessionUnavailable }
    | { NativeError: NativeError }
    | { Grabbing: Grabbing }
    | { Sde: Sde };
