// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./Notification";
import type { Ticks } from "./Ticks";

export type Detail = { "Ticks": Ticks } | { "Notification": Notification } | { "Stopped": boolean };
