// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DltFilterConfig = { min_log_level: number, app_ids: Array<string>, ecu_ids: Array<string>, context_ids: Array<string>, app_id_count: bigint, context_id_count: bigint, };
