// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DltFilterConfig } from "./DltFilterConfig";

export type DltParserSettings = { filter_config: DltFilterConfig | null, fibex_file_paths: Array<string>, with_storage_header: boolean, tz: string, };
