// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Aborted } from "./Aborted";
import type { Communication } from "./Communication";
import type { Config } from "./Config";
import type { Grab } from "./Grab";
import type { Input } from "./Input";
import type { IoOperation } from "./IoOperation";
import type { Regex } from "./Regex";

export type Error = { "Config": Config } | { "Communication": Communication } | { "IoOperation": IoOperation } | { "Regex": Regex } | { "Input": Input } | { "Grab": Grab } | { "Aborted": Aborted };
