// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentsUpdated } from "./AttachmentsUpdated";
import type { IndexedMapUpdated } from "./IndexedMapUpdated";
import type { NativeError } from "./NativeError";
import type { OperationDone } from "./OperationDone";
import type { OperationError } from "./OperationError";
import type { Progress } from "./Progress";
import type { SearchMapUpdated } from "./SearchMapUpdated";
import type { SearchUpdated } from "./SearchUpdated";
import type { SearchValuesUpdated } from "./SearchValuesUpdated";

export type Event = { "StreamUpdated": bigint } | { "FileRead": boolean } | { "SearchUpdated": SearchUpdated } | { "IndexedMapUpdated": IndexedMapUpdated } | { "SearchMapUpdated": SearchMapUpdated } | { "SearchValuesUpdated": SearchValuesUpdated } | { "AttachmentsUpdated": AttachmentsUpdated } | { "Progress": Progress } | { "SessionError": NativeError } | { "OperationError": OperationError } | { "OperationStarted": string } | { "OperationProcessing": string } | { "OperationDone": OperationDone } | { "SessionDestroyed": boolean };
