// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrabbedElement = { source_id: number, content: string, pos: bigint, nature: number, };
