// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from './GrabErrorInner';

export type GrabError = { error: Error | null };
