// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotInitialize } from './NotInitialize';
import type { Communication } from './Communication';
import type { Config } from './Config';
import type { InvalidRange } from './InvalidRange';
import type { Interrupted } from './Interrupted';
import type { IoOperation } from './IoOperation';
import type { Unsupported } from './Unsupported';

export type Error =
    | { Config: Config }
    | { Communication: Communication }
    | { IoOperation: IoOperation }
    | { InvalidRange: InvalidRange }
    | { Interrupted: Interrupted }
    | { Unsupported: Unsupported }
    | { NotInitialize: NotInitialize };
