// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrabError } from "./GrabError";

export type Grab = { error: GrabError | null, };
