// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeInclusive } from "./RangeInclusive";

export type InvalidRange = { range: RangeInclusive | null, context: string, };
