// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transition } from "./Transition";

export type LifecycleTransition = { transition: Transition | null, };
