// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserveOrigin } from "./ObserveOrigin";
import type { ParserType } from "./ParserType";

export type ObserveOptions = { origin: ObserveOrigin | null, parser: ParserType | null, };
