// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeError } from "./NativeError";

export type OperationError = { uuid: string, error: NativeError | null, };
