// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cancelled } from "./Cancelled";
import type { Finished } from "./Finished";

export type Outcome = { "Finished": Finished } | { "Cancelled": Cancelled };
