// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Empty } from "./Empty";
import type { StringVec } from "./StringVec";

export type Output = { "StringValue": string } | { "StringVecValue": StringVec } | { "OptionStringValue": string } | { "BoolValue": boolean } | { "Int64Value": bigint } | { "EmptyValue": Empty };
