// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessTransportConfig = { cwd: string, command: string, envs: { [key: string]: string }, };
