// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressDetail } from "./ProgressDetail";

export type Progress = { uuid: string, detail: ProgressDetail | null, };
