// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Request } from "./Request";

export type SdeRequest = { request: Request | null, };
