// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueRange } from "./ValueRange";

export type SearchValuesUpdated = { values: { [key: number]: ValueRange }, };
