// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from './SearchErrorInner';

export type SearchError = { error: Error | null };
