// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerialTransportConfig = { path: string, baud_rate: number, data_bits: number, flow_control: number, parity: number, stop_bits: number, send_data_delay: number, exclusive: boolean, };
