// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transport } from "./Transport";

export type Stream = { name: string, transport: Transport | null, };
