// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Started } from './Started';
import type { Stopped } from './Stopped';
import type { TicksWithUuid } from './TicksWithUuid';

export type Transition = { Started: Started } | { Ticks: TicksWithUuid } | { Stopped: Stopped };
