// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessTransportConfig } from "./ProcessTransportConfig";
import type { SerialTransportConfig } from "./SerialTransportConfig";
import type { TcpTransportConfig } from "./TcpTransportConfig";
import type { UdpTransportConfig } from "./UdpTransportConfig";

export type Transport = { "Process": ProcessTransportConfig } | { "Tcp": TcpTransportConfig } | { "Udp": UdpTransportConfig } | { "Serial": SerialTransportConfig };
