// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DltParserSettings } from "./DltParserSettings";
import type { SomeIpParserSettings } from "./SomeIpParserSettings";

export type Type = { "Dlt": DltParserSettings } | { "SomeIp": SomeIpParserSettings } | { "Text": boolean };
