// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MulticastInfo } from "./MulticastInfo";

export type UdpTransportConfig = { bind_addr: string, multicast: Array<MulticastInfo>, };
