[package]
name = "matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
fuzzy-matcher = "*"
serde_json = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"
