// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

// *** ATTENTION ***
// This type has been adjusted after code generation.
// Please make sure to not change it on further type generation if not intended.

/**
 * Describes the content of attached data found in the `payload` of a `dlt` message.
 */
export interface AttachmentInfo {
    /**
     * A unique identifier for the attachment.
     */
    uuid: string;
    /**
     * The full path to the file. Note that `chipmunk` serializes the file name to ensure proper
     * saving to disk, so the actual file name may differ from the value in the `name` field.
     */
    filepath: string;
    /**
     * The name of the application, usually corresponding to the file name.
     */
    name: string;
    /**
     * The file extension, if available.
     */
    ext: string | null;
    /**
     * The size of the file in bytes.
     */
    size: number;
    /**
     * The `mime` type of the file, if it could be determined.
     */
    mime: string | null;
    /**
     * The log entry numbers containing the application data. Note that the application
     * data may be contained in a single log entry or split into parts distributed
     * across sequential log entries.
     */
    messages: number[];
}

/**
 * A list of attachments.
 */
export type AttachmentList = Array<AttachmentInfo>;
