// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Used to delivery results of extracting values. That's used in the scope
 * of chart feature
 */
export type ExtractedMatchValue = {
    /**
     * The index of log entry (row number)
     */
    index: number;
    /**
     * List of matches:
     * `usize` - index of filter
     * `Vec<String>` - list of extracted values
     */
    values: Array<[number, Array<string>]>;
};

export type NearestPosition = { index: number; position: number };

/**
 *(row_number, min_value_in_range, max_value_in_range, value)
 * value - can be last value in range or some kind of average
 */
export type Point = { row: number; min: number; max: number; y_value: number };

export type ResultBool = boolean;

/**
 * The list of `ExtractedMatchValue`
 */
export type ResultExtractedMatchValues = Array<ExtractedMatchValue>;

export type ResultNearestPosition = NearestPosition | null;

/**
 * Scaled chart data
 */
export type ResultScaledDistribution = Array<Array<[number, number]>>;

export type ResultSearchValues = Map<number, Point[]>;

/**
 * Used only for debug session lifecycle
 */
export type ResultSleep = { sleep_well: boolean };

export type ResultU64 = number;
