// pub mod conversation;
// pub mod llm;

pub mod agents;

use log::{error, warn};
use ollama_rs::generation::chat::ChatMessage;
use rmcp::{
    RoleClient,
    model::{
        CallToolRequestParams, ClientCapabilities, ClientInfo, Implementation,
        InitializeRequestParams,
    },
    service::{RunningService, ServiceExt},
    transport::StreamableHttpClientTransport,
};
use serde_json::Value;
use tokio::{select, sync::mpsc};

use crate::{
    chat::Prompt,
    // client::llm::{Llm, LlmClient, LlmConfig},
    errors::McpError,
    types::Response,
};
use agents::LlmAgent;

// TODO:[MCP] store this in a single global location
pub const SERVER_ADDRESS: &str = "http://127.0.0.1:8181/mcp";

const SYSTEM_PROMPT: &str = r#"You are a log analysis assistant for Chipmunk.
Your goal is to help users analyze logs using the provided tools.
When you receive a prompt, often accompanied by sample log lines, analyze the user's intent and call the appropriate tool.

Rules for tool usage:
1. 'apply_search_filter': Use this for filtering logs.
   - 'value' is the search pattern.
   - 'is_regex' should be true if you use regex patterns (like \d+, [A-Z], etc.).
   - 'ignore_case' should be true if the user doesn't specify case sensitivity.
   - 'is_word' should be true if the user wants to match whole words only. Default to false.
2. If the user asks for a chart or values, use 'search_values' or 'get_chart_histogram'.
3. Always be precise with the parameters. If a parameter is not specified, use common-sense defaults.
4. Output ONLY the tool call if that's the primary action.

Sample log lines provided at the end of the prompt show the context and format of the current session. Use them to craft better search patterns.
"#;

pub struct McpConfig {
    pub url: String,
}

pub struct McpClient {
    prompt_rx: mpsc::Receiver<Prompt>,
    response_tx: mpsc::Sender<Response>,
}

impl McpClient {
    pub fn new() -> (Self, mpsc::Sender<Prompt>, mpsc::Receiver<Response>) {
        let (response_tx, response_rx) = mpsc::channel::<Response>(32);
        let (prompt_tx, prompt_rx) = mpsc::channel::<Prompt>(32);

        (
            Self {
                prompt_rx,
                response_tx,
            },
            prompt_tx,
            response_rx,
        )
    }

    pub async fn start(self) -> Result<(), McpError> {
        // Setup MCP connection
        let transport = StreamableHttpClientTransport::from_uri(SERVER_ADDRESS);
        let capabilities = ClientCapabilities::builder()
            .enable_elicitation()
            .enable_roots()
            .enable_sampling()
            .build();

        let implmentation =
            Implementation::new("mcp-client", String::from(env!("CARGO_PKG_VERSION")))
                .with_title("Chipmunk MCP Client");

        // TODO:[MCP] match with MCP server definition
        let client_info = ClientInfo::new(capabilities, implmentation);

        let mcp_service = client_info
            .serve(transport)
            .await
            .map_err(|e| McpError::Generic {
                message: e.to_string(),
            })?;

        // let llm = Llm::from_config(self.llm_config);

        tokio::spawn(async move {
            if let Err(e) = McpClient::run(
                self.prompt_rx,
                self.response_tx,
                mcp_service,
                // llm,
            )
            .await
            {
                error!("MCP client event loop ended: {:?}", e);
            }
        });
        Ok(())
    }

    async fn run(
        mut prompt_rx: mpsc::Receiver<Prompt>,
        response_tx: mpsc::Sender<Response>,
        mcp_service: RunningService<RoleClient, InitializeRequestParams>,
    ) -> Result<(), McpError> {
        // History array, which will be auto generated by the rmcp crate automatically based on the response from user
        // and LLM.
        let mut history = vec![ChatMessage::system(SYSTEM_PROMPT.to_string())];
        loop {
            select! {
                Some(prompt) = prompt_rx.recv() => {
                    let mut continue_chat: bool = true;
                    let mut user_prompt = format!("User prompt: {}\n\n session_id:\n{}", prompt.message, prompt.id);

                    let tools = mcp_service.list_tools(Default::default()).await?;

                    while continue_chat {
                        // Call the API with user prompt and history object.
                        let response = agents::GenericAgent::from_config(prompt.config.clone()).send_chat_message(user_prompt.clone(), &mut history, tools.clone()).await;

                        match response {
                            Ok(res) => {
                                let tool_calls = res.message.tool_calls.clone();

                                // If LLM did not call any function then there is nothing to do, if response contains
                                // the message then display that message to the user via channel and close the loop.
                                if tool_calls.is_empty() {
                                    continue_chat = false;
                                    if !res.message.content.is_empty() {
                                        let _ = response_tx.send(Response::Complete(res.message.content.clone())).await;
                                    }
                                }

                                // Call each tool in the tool calls.
                                for tool_call in tool_calls {
                                    // `complete_chat` marks the end of conversation, if LLM is calling this tool then chat is complete and
                                    // we should send correct response to the user and end the chat loop.
                                    if tool_call.function.name == "complete_chat" {
                                        continue_chat = false;
                                        let _ = response_tx.send(Response::Complete("Complete the task successfully".to_string())).await;
                                        let _ = response_tx.send(Response::Complete(res.message.content.clone())).await;
                                    }

                                    let param = CallToolRequestParams::new(tool_call.function.name.clone()).with_arguments(fetch_arguments(&tool_call));

                                    // Call MCP tool with tool params.
                                    match mcp_service.call_tool(param).await {
                                        Ok(tool_result) => {
                                            if tool_result.is_error.is_some_and(|x| x) {
                                                continue_chat = false;
                                                log::error!("Error while calling a tool from MCP {tool_result:?}");
                                            }
                                            // if tool call is
                                            user_prompt = tool_result
                                                .content
                                                .first()
                                                .and_then(|raw| raw.raw.as_text()).map(|content| content.text.clone())
                                                .unwrap_or_default();

                                            if user_prompt.is_empty() {
                                                user_prompt = String::from("Did not receive text result from MCP server; Call same tool again but check the parameters this time");
                                            }
                                            let _ = response_tx.send(Response::Progress(format!("Applied tool {}", tool_call.function.name))).await;
                                        },
                                        Err(e) => {
                                            error!("🔴 Tool call failed: {:?}", e);
                                            println!("🔴 Tool call failed: {:?}", e);
                                            let _ = response_tx.send(Response::Complete(String::from("Failed calling tool from application"))).await;

                                        }
                                    }
                                }
                            },
                            Err(err) => {
                                error!("🔴 MCP Client failed to get mock prompt response: {err:?}");
                            }
                        }
                    }
                }
            }
        }

        #[allow(unreachable_code)]
        Ok(())
    }
}

fn fetch_arguments(tool_call: &ollama_rs::generation::tools::ToolCall) -> rmcp::model::JsonObject {
    let args_value = tool_call.function.arguments.clone();
    let args_value = normalize_args_value(args_value);
    let args_object = match args_value {
        Value::Object(map) => map,
        Value::Null => {
            warn!(
                "⚠️ Tool call arguments are null; using empty parameters for {}",
                tool_call.function.name
            );
            serde_json::Map::new()
        }
        _ => {
            warn!(
                "⚠️ Tool call arguments are not an object for {}",
                tool_call.function.name
            );
            serde_json::Map::new()
        }
    };

    let mut json_obj = rmcp::model::JsonObject::new();
    for (key, value) in args_object {
        json_obj.insert(key, normalize_json_value(value));
    }

    warn!("☑️ Final call parameters are {json_obj:?}");
    json_obj
}

fn normalize_args_value(value: Value) -> Value {
    match value {
        Value::String(raw) => parse_jsonish_string(&raw),
        other => other,
    }
}

fn parse_jsonish_string(raw: &str) -> Value {
    let mut trimmed = raw.trim();
    if trimmed.is_empty() || trimmed.eq_ignore_ascii_case("null") {
        return Value::Null;
    }
    if trimmed.starts_with("```") {
        if let Some(end) = trimmed.rfind("```") {
            trimmed = &trimmed[3..end];
            if trimmed.trim_start().starts_with("json") {
                trimmed = trimmed.trim_start_matches("json").trim();
            }
        }
    }
    if trimmed.is_empty() || trimmed.eq_ignore_ascii_case("null") {
        return Value::Null;
    }
    let parsed = serde_json::from_str::<Value>(trimmed).unwrap_or_default();
    match parsed {
        Value::String(inner) => serde_json::from_str::<Value>(inner.trim()).unwrap_or_default(),
        other => other,
    }
}

fn normalize_json_value(value: Value) -> Value {
    match value {
        Value::String(raw) => serde_json::from_str::<Value>(&raw).unwrap_or(Value::String(raw)),
        Value::Array(items) => Value::Array(items.into_iter().map(normalize_json_value).collect()),
        Value::Object(map) => Value::Object(
            map.into_iter()
                .map(|(k, v)| (k, normalize_json_value(v)))
                .collect(),
        ),
        other => other,
    }
}
