[package]
name = "updater"
version = "0.2.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>", "oliver.mueller <oliver.mueller@esrlabs.com>"]
edition = "2024"

[dependencies]
dirs = "6.0"
log = "0.4"
log4rs = "1.3"
anyhow = "1.0"
regex = "1.7"
fs_extra = "1.3"
thiserror = "2.0"
tar = "0.4"
flate2 = "1.1"
toml = "0.8"
