[package]
name = "updater"
version = "0.2.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>", "oliver.mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[dependencies]
dirs = "4.0.0"
log = "0.4.17"
log4rs = "1.1.1"
anyhow = "1.0"
regex = "1.7.0"
fs_extra = "1.2.0"
thiserror = "1.0.38"
tar = "0.4.26"
flate2 = "1.0"
toml = "0.5.10"