##########################################################
### Minimum required versions for Chipmunk development ###
##########################################################

[cargo]
major = 1
minor = 81
patch = 0

[node]
major = 20
minor = 9
patch = 0

[npm]
major = 10
minor = 0
patch = 0

[yarn]
major = 1
minor = 22
patch = 0

[wasm_pack]
major = 0
minor = 13
patch = 0

[nj_cli]
major = 0
minor = 4
patch = 4
