[[bench]]
name = "mocks_once_producer"
library = "sources"

[[bench]]
name = "mocks_once_producer_jemalloc"
library = "sources"

[[bench]]
name = "mocks_once_producer_sysalloc"
library = "sources"

[[bench]]
name = "mocks_multi_producer"
library = "sources"

[[bench]]
name = "mocks_multi_producer_jemalloc"
library = "sources"

[[bench]]
name = "mocks_multi_producer_sysalloc"
library = "sources"

[[bench]]
name = "dlt_producer"
library = "sources"

[[bench]]
name = "someip_producer"
library = "sources"

[[bench]]
name = "someip_legacy_producer"
library = "sources"

[[bench]]
name = "text_producer"
library = "sources"

[[bench]]
name = "map_benchmarks"
library = "processor"

