[[bench]]
name = "map_benchmarks"
library = "processor"

[[bench]]
name = "dlt_producer"
library = "sources"

[[bench]]
name = "someip_producer"
library = "sources"

[[bench]]
name = "someip_legacy_producer"
library = "sources"

[[bench]]
name = "text_producer"
library = "sources"

[[bench]]
name = "mocks_once_producer"
library = "sources"

[[bench]]
name = "mocks_once_producer_jemalloc"
library = "sources"

[[bench]]
name = "mocks_once_producer_mimalloc"
library = "sources"

[[bench]]
name = "mocks_once_parallel"
library = "sources"

[[bench]]
name = "mocks_once_parallel_jemalloc"
library = "sources"

[[bench]]
name = "mocks_once_parallel_mimalloc"
library = "sources"

[[bench]]
name = "mocks_multi_producer"
library = "sources"

[[bench]]
name = "mocks_multi_producer_jemalloc"
library = "sources"

[[bench]]
name = "mocks_multi_producer_mimalloc"
library = "sources"

[[bench]]
name = "mocks_multi_parallel"
library = "sources"

[[bench]]
name = "mocks_multi_parallel_jemalloc"
library = "sources"

[[bench]]
name = "mocks_multi_parallel_mimalloc"
library = "sources"

