name: Handle new issues

on:
  issues:
    types:
      - opened

jobs:
  set-labels:
    runs-on: ubuntu-18.04
    steps:
      - name: Set issue defaults
        uses: meatlink/issue-defaults@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: new
          assignee: marcmo
