name: PublishRelease

on:
  release:
    types: [published]

jobs:
  invoke_package_distribution:
    name: Invoke chipmunk package creation and distribution for different package managers
    needs: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chipmunk-distribution
        uses: actions/checkout@v2
        with:
          repository: esrlabs/chipmunk-distribution
          path: "./chipmunk-distribution"
          token: ${{secrets.PUSH_TOKEN}}
      - name: Push tag
        working-directory: ./chipmunk-distribution
        run: |
          git config user.name "esrlabs"
          git config user.email "esrlabs@gmail.com"
          git remote set-url origin "https://esrlabs:${{secrets.PUSH_TOKEN}}@github.com/esrlabs/chipmunk-distribution"
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
