name: BuildAndReleaseChipmunk2

on:
    push:
        branches:
            - chipmunk_2 # Push events on chipmunk_2 branch
        tags-ignore:
            - next-**
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-18.04, windows-2019, macOS-latest]
                rust: [stable]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: chipmunk_2
            - name: Install windows python
              uses: actions/setup-python@v1
              if: startsWith(matrix.os, 'windows')
              with:
                  python-version: "2.7"
                  architecture: "x64" # (x64 or x86)
            - name: install ruby
              uses: actions/setup-ruby@v1
              with:
                  ruby-version: "2.x"
            - name: install dotenv
              run: gem install dotenv
            - name: install octokit
              run: gem install octokit
            - name: install node
              uses: actions/setup-node@master
              with:
                  node-version: "14.15.4"
            - name: install typescript
              if: "!startsWith(matrix.os, 'windows')"
              run: npm install --global typescript@3.7.3
            - name: install neon cli
              run: npm install --global neon-cli@0.3.1
            - name: install rust
              uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: ${{ matrix.rust }}
            - name: setup keychain for signing and notarising
              if: runner.os == 'macOS'
              env:
                  KEYCHAIN_NAME: "build.keychain"
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
              run: |
                  security create-keychain -p "$KEYCHAIN_PWD" "$KEYCHAIN_NAME"
                  security default-keychain -s "$KEYCHAIN_NAME"
                  certfile="${HOME}/buildcert.p12"
                  echo "$CSC_LINK" | base64 -d > "$certfile"
                  security import \
                    "$certfile" \
                    -P "$CSC_KEY_PASSWORD" \
                    -A \
                    -k "$KEYCHAIN_NAME"
                  rm "$certfile"
                  security set-key-partition-list \
                    -S 'apple:' \
                    -s \
                    -k "$KEYCHAIN_PWD" \
                    "$KEYCHAIN_NAME"
            - name: build release
              run: rake full_pipeline --trace
              env:
                  KEYCHAIN_NAME: "build.keychain"
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  APPLEID: ${{ secrets.APPLEID }}
                  APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
                  SIGNING_ID: ${{ secrets.SIGNING_ID }}
                  KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: ls
            - name: Release
              uses: meatlink/action-gh-release@fix-econnreset
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      *.tgz
                      *.zip
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
