/// Interface used for shard types among all plugins 
interface shared-types {

  /// Error type while initializing the plugins
  variant init-error {
    config(string),
    io(string),
    unsupported(string),
    other(string),
  }
}

/// Logging definitions and methods for all plugins
interface logging {

  /// Log Level 
  enum level {
    error,
    warn,
    info,
    debug,
    trace,
  }

  /// Log the given message with current log level if log level is allowed
  log: func(level: level, msg: string);
}
