//! Frame-local events that coordinate session UI components.

use processor::search::filter::SearchFilter;

/// Ephemeral signals generated by UI components during a render frame.
///
/// These signals are collected in `SessionShared` and processed by the
/// `SessionUI` controller at the end of the frame to handle state changes
/// that require mutable access to the parent.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SessionSignal {
    /// Indicates that search has been dropped in last frame.
    SearchDropped,
    /// Synchronizes search-bar controls after applying a copied temporary search.
    TempSearchApplied(SearchFilter),
    /// Requests capturing the current session filters and charts as a preset.
    CapturePreset,
}
